### ISSUE TITLE
Set default parameters after component installation

### ISSUE THREAD

**Issue by stevenrombauts** [joomlatools/joomlatools-platform#232]
Installing a component that has a config.xml will not load the default values into the `params` column in the  `extensions` table. This breaks the default behaviour of some components such as com_content.

Port the logic from joomlatools/joomla-platform-content#11 over into the `JInstallerAdapterComponent` class.

**Comment by manchumahara** [comment]
Is this issue merged in joomla core yet ?

**Comment by johanjanssens** [comment]
For questions please use our community chat: https://gitter.im/joomlatools/dev or mailing list: https://groups.google.com/forum/#!forum/joomlatools-dev
