### ISSUE TITLE
Composer install fails when installing extensions

### ISSUE THREAD

**Issue by johanjanssens** [joomlatools/joomlatools-platform#240]
Running `composer install` fails when the `composer.json` includes dependencies that require the joomlatools-installer

Following error will be thrown : 

`PHP Warning:  Uncaught exception 'ErrorException' with message 'require_once(/var/www/joomla-platform/vendor/autoload.php): failed to open stream: No such file or directory' in /var/www/joomla-platform/lib/libraries/cms.php:34`

Note : Depending on the order the dependencies are installed this issue might not happen.

**Comment by johanjanssens** [comment]
Related issue joomlatools/joomla-composer#15

**Comment by johanjanssens** [comment]
@stevenrombauts Would fix this problem by including the phpdotenv library in the /lib/libraries folder. Thoughts ?

**Comment by stevenrombauts** [comment]
@johanjanssens Yes that should work (re joomlatools/joomla-composer#15)

**Comment by johanjanssens** [comment]
@stevenrombauts If you agree we can close this issue here then ?

**Comment by johanjanssens** [comment]
@stevenrombauts Can you review this ? I have moved the phpdotenv into a git submodule and changed the way it's loaded. 

I suspect we need to add an additional check to see if the autoload.php exists and only include it if it does ?

**Comment by johanjanssens** [comment]
As discussed moving this to 1.1. One other things we can look into is if we can add phpdotenv and other dependencies to he Joomlatools Installer, needs to be tested if this would make those dependencies be installed first or not.

**Comment by johanjanssens** [comment]
@stevenrombauts Can we handle this by adding the phpdotenv library as a dependency to the installer and see if that solves it ?

**Comment by stevenrombauts** [comment]
@johanjanssens The autoloader issue has been solved in joomlatools/joomlatools-composer#22 and is currently merged into the plugin's develop branch awaiting a final test from @raeldc. 

Marking this ticket as invalid.
