### ISSUE TITLE
Ensure PHP7 compatibility

### ISSUE THREAD

**Issue by stevenrombauts** [joomlatools/joomlatools-platform#247]
Ensure Platform runs on php7. Related PR's

- joomla/joomla-cms#6600
- joomla/joomla-cms#8340
- joomla/joomla-cms#7198
- joomla/joomla-cms#7065

**Comment by johanjanssens** [comment]
@stevenrombauts Did initial check on the 7.0.0RC5 base platform setup and cannot find immediate issue. Need to install the additional extensions and see if any of those throws errors.
