### ISSUE TITLE
New administrator template

### ISSUE THREAD

**Issue by tomjanssens** [joomlatools/joomlatools-platform#260]
Implement new administrator template.

**Comment by tomjanssens** [comment]
@johanjanssens ready for testing, new database install required.

**Comment by johanjanssens** [comment]
@tomjanssens Thanks. Good work. Few points of feedback :

1. The debug permissions report is not styled yet. Go to user > and debug permissions report
2. The permissions settings for each component are not styled yet. Go to settings > permissions
3. If you go to system > modules and you click on a filter the right pane moves. Also do we need select2 for all those dropdowns ? I takes a while to load and makes the screen jump when loaded.
4. Clicking the little wheel on the right top gives a dropdown that doesn't seems to be fully styled yet.

Thats it so far after a first round of testing.

**Comment by tomjanssens** [comment]
@johanjanssens feedback has been fixed:

1. Fixed
2. Fixed
3. Unable to reproduce on Chrome stable channel, are you using Canary?
4. Fixed

**Comment by yiendos** [comment]
Looking really good @tomjanssens @robinpoort a few issues I have found.

Details
Browser	Chrome
Browser Version	46.0.2490.86
User Agent String	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36
OS Type	Macintosh
OS Name	OS X
Capture Time	2015-11-27 10:22:43 UTC
Javascript	true
Cookies	true
Color Depth	24
Screen	1440 x 900
Browser	1394 x 783
Flash	19.0.-1
Java	false
Language	en-US


**Snag list:** 

1. Clicking the context menu, and then clicking the standard toolbar 'Please make a selection from the list', dispite the radio checkbox being selected... Takes a few more clicks away from the menu and deselect the checkbox in order for the toolbar to work once more:
http://joomla-platform.dev/administrator/index.php?option=com_modules&view=modules

2. When editing a record, maybe the admin menu navbar could be more clear that it has been disabled 

3. sortable modules doesn't seem to be working: 
http://joomla-platform.dev/administrator/index.php?option=com_modules&view=modules

4. Select2 drop downs in their intial state... unclicked seem a little flat compare to the bootstrap styling of other inputs... Account details vs Basic Settings: 
http://joomla-platform.dev/administrator/index.php?option=com_users&view=profile&layout=edit&id=951

4. Clicking users from the main dashboard sidebar sends the component a little crazy... seems to attempt to wrap the component in the login screen

5. Doesn't seem to be any easy way to return to the dashboard... I would expect to click the top left joomla icon to return but doesn't work

**Comment by robinpoort** [comment]
Extra explanation for Issue 1:

On the following screen:
`/administrator/index.php?option=com_modules&view=modules`

If for example you click the context menu (caret next to the check icon in the table) and then click away from the context menu, the checkbox is highlighted

But then clicking the traditional toolbar > Edit gives you 'Please first make a selection from the list'

**Comment by robinpoort** [comment]
Extra explanation for Issue 4:

Try to make the select2 look a lot more like the bootstrap select lists. 
https://fk.github.io/select2-bootstrap-css/

**Comment by robinpoort** [comment]
Issue 6 has been done on purpose since there's currently nothing to see on the dashboard anyways

**Comment by robinpoort** [comment]
Issue 3 is halfly working. You have to click on the table header first but that doesn't seem to be possible when `footable` or `floatThead` is enabled. You can disable these JS libraries temporary by removing the `table--fixed` and `footable` classes from the table and reload the page.

**Comment by robinpoort** [comment]
Issue 1 has it's own ticket and can be found here: #285 
Issue 2 is fixed
Issue 3 has it's own ticket and can be found here: #287 
Issue 4 has it's own ticket and can be found here: #286 
Issue 5 has it's own ticket and can be found here: #288
Issue 6 is fixed

**Comment by johanjanssens** [comment]
@robinpoort Good work. Getting ready to push this one out as the 1.1 release. One final remark. Would like to rename the template to 'Elysium/Elysio'

In Homer’s Odyssey, Elysium is described as a paradise: *to the Elysian plain…where life is easiest for men. No snow is there, nor heavy storm, nor ever rain, but ever does Ocean send up blasts of the shrill-blowing West Wind that they may give cooling to men.*

See : 

- https://en.wikipedia.org/wiki/Elysium
- https://en.wikipedia.org/wiki/Elysium_(film)

**Comment by robinpoort** [comment]
@johanjanssens @tomjanssens Would go for Elysio then I guess :) Sounds more like a "thing" you can use where Elysium sounds more like something that "is"

Pros: There's some thought behind it. Paradise after the Joomla storm
Cons: It might be hard to pronounce / remember

Anyways there's more thought behind this thing than backman. Although backman fits nice with our existing products.

**Comment by johanjanssens** [comment]
Elysio it is. 

About backman, thing is if we plan to release it as a 'product' we can still use the name backman for it, for platform I wouldn't do that. It also makes for a nice story and concept for the announcement :)

**Comment by robinpoort** [comment]
Agreed :)

**Comment by johanjanssens** [comment]
@tomjanssens @robinpoort Template has been renamed to "Elysio". Is more work still ongoing on the template ? If not, I would like to prepare the 1.1 release.

**Comment by robinpoort** [comment]
@johanjanssens It's got the same issues as https://github.com/cta-int/joomla-platform/issues/41#issuecomment-177628879

**Comment by johanjanssens** [comment]
@robinpoort Should we create separate issues for them, I noticed you have already created separate tickets for the UI, or should we handle them as part of this issue ?

**Comment by robinpoort** [comment]
We can handle them separate. Issues are indeed created a while ago so then this one can close for now I think

**Comment by johanjanssens** [comment]
@robinpoort Good work. This PR has now been merged into develop. Further changes or problems we will tackle in new issues as agreed.
