### ISSUE TITLE
Checkbox / toolbar issue

### ISSUE THREAD

**Issue by robinpoort** [joomlatools/joomlatools-platform#285]
On the following screen:
http://joomla.box/joomlatools-platform/administrator/index.php?option=com_modules&view=modules

If you click the context menu (caret next to the check icon in the table, gives a dropdown) and then click away from the context menu, the checkbox is highlighted

But then clicking the traditional toolbar > `Edit` gives you 'Please first make a selection from the list'

What needs to happen:
1. Clicking the caret should never highlight the table row
2. Clicking the table row doesn't properly `click` the checkbox. Clicking table row and then `Edit` doesn't work. This needs to be fixed.

**Comment by johanjanssens** [comment]
@robinpoort Are the fixes needed here css/js or related to the PHP code ?

**Comment by robinpoort** [comment]
@johanjanssens I'm guessing JS related. Could be a wrong class name to the markup as well. In that case we can either change the JS or the markup

**Comment by johanjanssens** [comment]
@allanpilarca Can you check if this issue still exists in platform and if so try to fix it?
