### ISSUE TITLE
Gitignore ignores lib/libraries/joomla/log

### ISSUE THREAD

**Issue by stevenrombauts** [joomlatools/joomlatools-platform#289]
The .gitignore file has a line with `log` in it. This will exclude *all* directories that are called `log`, such as `lib/libraries/joomla/log`.

From the git docs:

> If the pattern does not contain a slash /, git treats it as a shell glob pattern and checks for a match against the pathname relative to the location of the .gitignore file (relative to the toplevel of the work tree if not from a .gitignore file).
> 
> A leading slash matches the beginning of the pathname. For example, "/*.c" matches "cat-file.c" but not "mozilla-sha1/sha1.c".

**Comment by johanjanssens** [comment]
@stevenrombauts This is a leftover from the Joomla CMS ignore file. Something to be fixed indeed.
