### ISSUE TITLE
Should not allow to delete all presets

### ISSUE THREAD

**Issue by itsromack** [joomlatools/joomlatools-platform#312]
**If all presets are deleted**, the user will only see **blank** admin page on re-login.

[http://localhost/administrator/index.php?option=com_users&view=levels](http://localhost/administrator/index.php?option=com_users&view=levels)

**Comment by johanjanssens** [comment]
Hello Romack, we appreciate bug reports, we love PR's! If you do not know how to fix this issue please use [our forums](https://groups.google.com/forum/#!forum/joomlatools-dev) to explain and discuss it. If you know how to fix it, feel free to submit a PR. You can find our contribution guidelines here: https://www.joomlatools.com/developer/contribute/
