### ISSUE TITLE
Allow extension updates if codebase is missing

### ISSUE THREAD

**Issue by stevenrombauts** [joomlatools/joomlatools-platform#313]
To make it possible to install extensions using Composer in a CI workflow, we need an extension update to work without an existing codebase.

Example:
- You install joomlatools/platform-content into your codebase using Composer
- Database tables are created, extension elements are added to the `extensions` table
- You deploy your database to your production server
- You deploy using Capistrano and run `composer install` on every deployment. Result: database entries already created but the extension files are not installed yet.
- Installer will error out because of duplicated entries/tables in database

Solution:
- Composer plugin will do an upgrade() instead of install() when the element is already present in the database. See joomlatools/joomlatools-composer#23
- Platform needs run an update() without erroring out. At a certain point in time it will look for the old manifest which results in exceptions. See: https://github.com/joomlatools/joomlatools-platform/blob/master/lib/libraries/cms/installer/adapter/component.php#L632-L650

**Comment by johanjanssens** [comment]
@stevenrombauts Could you give some pointers here as to where and how this should be fixed?

**Comment by stevenrombauts** [comment]
@johanjanssens The suggested solutions above are as far as I got at that time too. The problem in a nutshell:

1. We don't commit Composer installed extensions into the repo. In this case, this means the different com_extension directories throughout admin, components, media for all the 3rd party packages.
1. In our continuous flow, we run Composer install on deploy time. Meaning, we install again.
1. Because of **1**, we error out:
    1. Composer installer isn't yet smart enough to figure out if the extension is installed because the files are missing, so triggers an `install` instead of `update`. I _think_ this can be fixed by examining the `extensions` table.
    1. Platform has trouble running an `update` because the extension files are not present. It seems to fail when looking for the extension manifest. I _think_ this can be solved by looking for it in the manifests stored in the extensions table (or maybe even in vendor dir)

Does that make sense?

**Comment by johanjanssens** [comment]
@stevenrombauts Got it. So the problem is two fold:

1. Extension installations/updates
2. Platform updates

we are going to need to change the Joomla installer to check the database and not the file system. 
Should these fixes by made in the composer installer then? Making it examine the database to find out of an extension is installed or not and then install/update from there?

**Comment by stevenrombauts** [comment]
As discussed this issue will be solved by using symlinks and git submodules to include dependencies that need to be included outside the vendor directory. The Composer method is proving too complicated and error-prone to make this worth our time. (see https://github.com/joomlatools/www.joomlatools.com/issues/940)
