### ISSUE TITLE
Fix "Require Password Reset"

### ISSUE THREAD

**Issue by stevenrombauts** [joomlatools/joomlatools-platform#314]
When enabling the "Require Password Reset" for a user, the user can't do anything once logged in. Resulting page:

![screen shot 2016-04-25 at 13 13 54](https://cloud.githubusercontent.com/assets/77368/14783476/c0665aea-0ae7-11e6-99ae-b4c3adec3cb4.png)

We should remove the option or make it work again. 

_Update_: this fails with a Manager account. An administrator or super administrator works.

**Comment by johanjanssens** [comment]
@stevenrombauts How do I replicate this?

**Comment by stevenrombauts** [comment]
@johanjanssens Steps to reproduce:

1. Create a new user in Manager group
1. Enable "Require password reset"
1. Log in as Manager in back-end: you will get a permission error.

The screenshot above is front-end: this is working now in current master. Back-end is still an issue: 

The password reset form in back-end used to be in `com_admin`, we moved this to 
`com_users`. The commit above fixes the redirect to it.

The issue that remains is that a Manager does not have permission to access `com_users` admin by default. Should we simply allow it now, or find another fix?

**Comment by johanjanssens** [comment]
@stevenrombauts I see the issues. I moved things indeed to clean up the code, lets fix this by allowing a manager to access com_users admin. Can you handle that?

**Comment by stevenrombauts** [comment]
@johanjanssens Ok, updated the data SQL to give Managers access to com_users.
