### ISSUE TITLE
Set PHP7 as minimal requirement

### ISSUE THREAD

**Issue by johanjanssens** [joomlatools/joomlatools-platform#322]
Set PHP7 as the minimal requirement.

**Comment by johanjanssens** [comment]
@allanpilarca Can a PR be created for this so we can close it?

**Comment by allanpilarca** [comment]
@johanjanssens there is already a PR for this, here is the link https://github.com/joomlatools/joomlatools-platform/pull/352

**Comment by johanjanssens** [comment]
Approved.
