### ISSUE TITLE
Prepare 2.0.0 Release

### ISSUE THREAD

**Issue by allanpilarca** [joomlatools/joomlatools-platform#342]
Prepare 2.0.0 Release

**Comment by johanjanssens** [comment]
@allanpilarca The readme's need to be updated across the board:

1. PHP version changed to 7
2. Joomla fork is now 3.6.5
3. Composer require changed to 2.* 

Update composer version and also update composer to set php to min 7. Should be done for all component repo's too.

**Comment by johanjanssens** [comment]
@allanpilarca What is the status of this one?

**Comment by allanpilarca** [comment]
@johanjanssens after closing this remaining PR https://github.com/joomlatools/joomlatools-platform/pull/352 we can now release 2.0.0

**Comment by johanjanssens** [comment]
Excellent, approved #352. All yours to finish off.
