### ISSUE TITLE
JError Does Not Exist in 404.php

### ISSUE THREAD

**Issue by magneticmg** [joomlatools/joomlatools-platform#366]
Hey Joomlatools!

https://github.com/joomlatools/joomlatools-platform/blob/master/lib/plugins/system/404/404.php#L20

This throws and error as JError doesn't exist in the platform (as far as I can see).

**Comment by johanjanssens** [comment]
@magneticmg We moved JError into the legacy package to clean up the core a bit more. Installing it should solve the issue: https://github.com/joomlatools/joomlatools-platform-legacy

**Comment by johanjanssens** [comment]
In future, for questions please use chat or forums! Thanks.
