### ISSUE TITLE
Output valid html5 script tag in document head

### ISSUE THREAD

**Issue by waseemsadiq** [joomlatools/joomlatools-platform#368]
**Bug**: Joomla currently outputs an invalid `<script>` tag for `scriptDeclarations`. Although it checks for `$doc->isHtml5(true)` before outputting individial scripts it doesn't do that same check for script declarations.

**Fix**: Add a `$doc->isHtml5(true)` check in `[/lib/libraries/joomla/document/html/renderer/head.php](https://github.com/joomlatools/www.joomlatools.com/blob/master/lib/libraries/joomla/document/html/renderer/head.php#L187)`

**Comment by waseemsadiq** [comment]
@johanjanssens @ercanozkaya I had a look but I couldn't quite figure out how to edit the file `/lib/libraries/joomla/document/html/renderer/head.php`. - so I've tagged you :)

I saw that it is extending `/lib/libraries/joomla/document/renderer/html/head.php` but I didn't know how to add the fix  _I'm new around here_ 

**[/lib/libraries/joomla/document/renderer/html/head.php#L220](https://github.com/joomlatools/joomlatools-platform/blob/9a038864b6f9a7648a07ec0e8085685ed18235de/lib/libraries/joomla/document/renderer/html/head.php#L220)**

From:
`$buffer .= $tab . '<script  type="text/javascript">' . $lnEnd;`
To:
`$buffer .= $tab . '<script'.($document->isHtml5() ? ' type="text/javascript"' : '').'>' . $lnEnd;`

**Comment by waseemsadiq** [comment]
It looks like this should already be fixed 🤷‍♂ 

[/lib/libraries/joomla/document/renderer/html/head.php#L246](https://github.com/joomlatools/joomlatools-platform/blob/9a038864b6f9a7648a07ec0e8085685ed18235de/lib/libraries/joomla/document/renderer/html/head.php#L246)

**Comment by waseemsadiq** [comment]
I'm gonna guess that maybe the site's version of platform is behind master?

**Comment by johanjanssens** [comment]
@waseemsadiq It is, i'm updating the site to the latest version of platform here: https://github.com/joomlatools/www.joomlatools.com/issues/943
